name: Mirror the Github organization repos to Gitee.
on:
  push:
    branches:
      - gh-pages
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
          src: github/chronicle12345
          dst: gitee/chronicle123
          dst_key: ${{secrets.GITEE_PRIVATE_KEY}}
          dst_token: ${{secrets.GITEE_TOKEN}}
          clone_style: "ssh"
          static_list: "undercat_blog"
          force_update: true
          debug: true
