name: Sync to Gitee
on:
  push:
    branches:
      - gh-pages
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      with:
        source-repo: https://github.com/chronicle12345/undercat_blog.git
        destination-repo: git@gitee.com:chronicle123/undercat_blog.git
