name: Mirror the Github organization repos to Gitee.
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
          src: github/chronicle12345
          dst: gitee/chronicle12345
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "undercat_blog"
          # force_update: true
          # debug: true
